### ISSUE TITLE
Slicer profile for SL1S?

### ISSUE THREAD

**Issue by InsulinGuy** [mayermakes/Engineering-Resin#1]
I'd like to try the resin on my Prusa SL1S, using prusa slicer.
Do you know if anyone already figured out the settings?

**Comment by mayermakes** [comment]
I have no access to a Prusa Sl1 at the moment, but I'll whip up a profile based on what works on other machines t ogive you a starting point.

**Comment by mayermakes** [comment]
![PrusaSL1 settings](https://user-images.githubusercontent.com/49558118/155598720-c4b404b5-b632-448f-be3e-4b0264218300.png)
Seems Prusaslicer does not allow to only export a single material config. 
So here is a screenshot of Values I suggest starting with. Do an exposure test and adjust the values down in second increments.
On older machines: Bottom layers are ususaally betewwn 60-40s and normal layers 15-12s
on newer machines with monochrome screens: bottom layers are 30-20s and normal layers 8-5s
Hope that gets you started. I also upload that screenshot to the profiles section.

**Comment by InsulinGuy** [comment]
Super cool!
I'll test and post my results here.
Vielen Dank
